os: linux
dist: focal
language: shell
services:
  - mongodb 	  # 4.0
  - mysql 	    # 5.7
  - redis 	    # 5.5
  - postgresql 	# 9.3 9.4 9.5 9.6 10 11
install: true
script:
  - git              --version  # 2.27.0
  - git-lfs          --version  # 2.9.2
  - hg               --version  # 5.3
  - svn              --version  # 1.13.0
  - cmake            --version  # 3.12.4
  - gcc              --version  # 9.3.0
  - ccache           --version  # 3.7.7
  - shellcheck       --version  # 0.7.0
  - shfmt            --version  # 2.6.3
  - docker           --version  # 19.03.8
  - docker-compose   --version  # 1.23.1
  # Ruby =====================
  - rvm              --version  # 1.29.10
  - which -a ruby
  - /home/travis/.rvm/rubies/ruby-2.7.0/bin/ruby --version  # 2.7.0p0
  - /usr/bin/ruby    --version  # 2.7.0p0
  - /bin/ruby        --version  # 2.7.0p0
  # Python ===================
  - pyenv            --version  # 1.1.5
  - which -a python
  - /usr/bin/python  --version  # 3.8.2
  - /bin/python      --version  # 3.8.2
  - which -a python3
  - /usr/bin/python3 --version  # 3.8.2
  - /bin/python3     --version  # 3.8.2
  - python3.5        --version || true  # not found
  - python3.6        --version || true  # not found
  - python3.7        --version || true  # not found
  - python3.8        --version  # 3.8.2
  - python -m pip    --version  # pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)
  - pip              --version  # pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)
  - python3 -m pip   --version  # pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)
  - pip3             --version  # pip 20.0.2 from /usr/lib/python3/dist-packages/pip (python 3.8)
  - pip install --upgrade pip   # Successfully installed pip-20.1.1
  - which -a python2   || true  # not found
  - which -a python2.7 || true  # not found
  - which -a pypy      || true  # not found
  - which -a pypy3     || true  # not found
  # Node.js ==================
  - nvm              --version  # 0.35.3
  # Go =======================
  - go                 version  # go1.11.1
  - gradle           --version || true  # not found
  - maven            --version || true  # not found
  - groovy           --version || true  # not found
  # PHP ======================
  - phpenv           --version  # rbenv 1.1.2-30-gc879cb0
  - which -a php
  - ls /home/travis/.phpenv/shims  # composer  php  phpunit
  # which java  || true
  # which javac || true
  java version || true
  java -version || true
  javac version || true
  javac -version || true
  

notifications:
  on_success: never
  on_failure: never
